import { z } from 'zod';

export const AfiliadoSchema = z.object({
  id: z.number().int(),
  folio: z.number().int(),
  apellidoPaterno: z.string().max(255).nullable(),
  apellidoMaterno: z.string().max(255).nullable(),
  nombre: z.string().max(200).nullable(),
  curp: z.string().max(18).nullable(),
  rfc: z.string().max(13).nullable(),
  numeroSeguroSocial: z.string().max(50).nullable(),
  fechaNacimiento: z.string().date().nullable(),
  entidadFederativaNacId: z.number().int().nullable(),
  domicilioCalle: z.string().max(255).nullable(),
  domicilioNumeroExterior: z.string().max(50).nullable(),
  domicilioNumeroInterior: z.string().max(50).nullable(),
  domicilioColonia: z.string().max(255).nullable(),
  domicilioCodigoPostal: z.number().int().nullable(),
  telefono: z.string().max(10).nullable(),
  estadoCivilId: z.number().int().nullable(),
  sexo: z.string().max(1).nullable(),
  correoElectronico: z.string().max(255).nullable(),
  estatus: z.boolean(),
  interno: z.number().int().nullable(),
  noEmpleado: z.string().max(20).nullable(),
  localidad: z.string().max(150).nullable(),
  municipio: z.string().max(150).nullable(),
  estado: z.string().max(150).nullable(),
  pais: z.string().max(100).nullable(),
  dependientes: z.number().int().nullable(),
  poseeInmuebles: z.boolean().nullable(),
  fechaCarta: z.string().date().nullable(),
  nacionalidad: z.string().max(80).nullable(),
  fechaAlta: z.string().date().nullable(),
  celular: z.string().max(15).nullable(),
  expediente: z.string().max(50).nullable(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime()
});

export const CreateAfiliadoSchema = z.object({
  folio: z.number().int(),
  apellidoPaterno: z.string().max(255).nullable().optional(),
  apellidoMaterno: z.string().max(255).nullable().optional(),
  nombre: z.string().max(200).nullable().optional(),
  curp: z.string().max(18).nullable().optional(),
  rfc: z.string().max(13).nullable().optional(),
  numeroSeguroSocial: z.string().max(50).nullable().optional(),
  fechaNacimiento: z.string().date().nullable().optional(),
  entidadFederativaNacId: z.number().int().nullable().optional(),
  domicilioCalle: z.string().max(255).nullable().optional(),
  domicilioNumeroExterior: z.string().max(50).nullable().optional(),
  domicilioNumeroInterior: z.string().max(50).nullable().optional(),
  domicilioColonia: z.string().max(255).nullable().optional(),
  domicilioCodigoPostal: z.number().int().nullable().optional(),
  telefono: z.string().max(10).nullable().optional(),
  estadoCivilId: z.number().int().nullable().optional(),
  sexo: z.string().max(1).nullable().optional(),
  correoElectronico: z.string().max(255).nullable().optional(),
  estatus: z.boolean().optional().default(true),
  interno: z.number().int().nullable().optional(),
  noEmpleado: z.string().max(20).nullable().optional(),
  localidad: z.string().max(150).nullable().optional(),
  municipio: z.string().max(150).nullable().optional(),
  estado: z.string().max(150).nullable().optional(),
  pais: z.string().max(100).nullable().optional(),
  dependientes: z.number().int().nullable().optional(),
  poseeInmuebles: z.boolean().nullable().optional(),
  fechaCarta: z.string().date().nullable().optional(),
  nacionalidad: z.string().max(80).nullable().optional(),
  fechaAlta: z.string().date().nullable().optional(),
  celular: z.string().max(15).nullable().optional(),
  expediente: z.string().max(50).nullable().optional()
});

export const UpdateAfiliadoSchema = z.object({
  apellidoPaterno: z.string().max(255).nullable().optional(),
  apellidoMaterno: z.string().max(255).nullable().optional(),
  nombre: z.string().max(200).nullable().optional(),
  curp: z.string().max(18).nullable().optional(),
  rfc: z.string().max(13).nullable().optional(),
  numeroSeguroSocial: z.string().max(50).nullable().optional(),
  fechaNacimiento: z.string().date().nullable().optional(),
  entidadFederativaNacId: z.number().int().nullable().optional(),
  domicilioCalle: z.string().max(255).nullable().optional(),
  domicilioNumeroExterior: z.string().max(50).nullable().optional(),
  domicilioNumeroInterior: z.string().max(50).nullable().optional(),
  domicilioColonia: z.string().max(255).nullable().optional(),
  domicilioCodigoPostal: z.number().int().nullable().optional(),
  telefono: z.string().max(10).nullable().optional(),
  estadoCivilId: z.number().int().nullable().optional(),
  sexo: z.string().max(1).nullable().optional(),
  correoElectronico: z.string().max(255).nullable().optional(),
  estatus: z.boolean().optional(),
  interno: z.number().int().nullable().optional(),
  noEmpleado: z.string().max(20).nullable().optional(),
  localidad: z.string().max(150).nullable().optional(),
  municipio: z.string().max(150).nullable().optional(),
  estado: z.string().max(150).nullable().optional(),
  pais: z.string().max(100).nullable().optional(),
  dependientes: z.number().int().nullable().optional(),
  poseeInmuebles: z.boolean().nullable().optional(),
  fechaCarta: z.string().date().nullable().optional(),
  nacionalidad: z.string().max(80).nullable().optional(),
  fechaAlta: z.string().date().nullable().optional(),
  celular: z.string().max(15).nullable().optional(),
  expediente: z.string().max(50).nullable().optional()
}).refine(
  (data) => Object.keys(data).length > 0,
  { message: 'At least one field must be provided for update' }
);