import { z } from 'zod';

export const PersonalSchema = z.object({
  interno: z.number().int(),
  curp: z.string().max(18).nullable(),
  rfc: z.string().max(13).nullable(),
  noempleado: z.string().max(10).nullable(),
  nombre: z.string().max(72).nullable(),
  apellido_paterno: z.string().max(20).nullable(),
  apellido_materno: z.string().max(20).nullable(),
  fecha_nacimiento: z.string().date().nullable(),
  seguro_social: z.string().max(11).nullable(),
  calle_numero: z.string().max(40).nullable(),
  fraccionamiento: z.string().max(40).nullable(),
  codigo_postal: z.string().max(5).nullable(),
  telefono: z.string().max(15).nullable(),
  sexo: z.string().max(1).nullable(),
  estado_civil: z.string().max(11).nullable(),
  localidad: z.string().max(25).nullable(),
  municipio: z.number().int().nullable(),
  estado: z.number().int().nullable(),
  pais: z.number().int().nullable(),
  dependientes: z.number().int().nullable(),
  posee_inmuebles: z.string().max(1).nullable(),
  fecha_carta: z.string().datetime().nullable(),
  email: z.string().max(30).nullable(),
  nacionalidad: z.string().max(1).nullable(),
  fecha_alta: z.string().datetime().nullable(),
  celular: z.string().max(15).nullable(),
  expediente: z.string().max(1).nullable(),
  f_expediente: z.string().datetime().nullable(),
  fullname: z.string().nullable()
});

export const CreatePersonalSchema = z.object({
  interno: z.number().int(),
  curp: z.string().max(18).nullable().optional(),
  rfc: z.string().max(13).nullable().optional(),
  noempleado: z.string().max(10).nullable().optional(),
  nombre: z.string().max(72).nullable().optional(),
  apellido_paterno: z.string().max(20).nullable().optional(),
  apellido_materno: z.string().max(20).nullable().optional(),
  fecha_nacimiento: z.string().date().nullable().optional(),
  seguro_social: z.string().max(11).nullable().optional(),
  calle_numero: z.string().max(40).nullable().optional(),
  fraccionamiento: z.string().max(40).nullable().optional(),
  codigo_postal: z.string().max(5).nullable().optional(),
  telefono: z.string().max(15).nullable().optional(),
  sexo: z.string().max(1).nullable().optional(),
  estado_civil: z.string().max(11).nullable().optional(),
  localidad: z.string().max(25).nullable().optional(),
  municipio: z.number().int().nullable().optional(),
  estado: z.number().int().nullable().optional(),
  pais: z.number().int().nullable().optional(),
  dependientes: z.number().int().nullable().optional(),
  posee_inmuebles: z.string().max(1).nullable().optional(),
  fecha_carta: z.string().datetime().nullable().optional(),
  email: z.string().max(30).nullable().optional(),
  nacionalidad: z.string().max(1).nullable().optional(),
  fecha_alta: z.string().datetime().nullable().optional(),
  celular: z.string().max(15).nullable().optional(),
  expediente: z.string().max(1).nullable().optional(),
  f_expediente: z.string().datetime().nullable().optional()
});

export const UpdatePersonalSchema = z.object({
  curp: z.string().max(18).nullable().optional(),
  rfc: z.string().max(13).nullable().optional(),
  noempleado: z.string().max(10).nullable().optional(),
  nombre: z.string().max(72).nullable().optional(),
  apellido_paterno: z.string().max(20).nullable().optional(),
  apellido_materno: z.string().max(20).nullable().optional(),
  fecha_nacimiento: z.string().date().nullable().optional(),
  seguro_social: z.string().max(11).nullable().optional(),
  calle_numero: z.string().max(40).nullable().optional(),
  fraccionamiento: z.string().max(40).nullable().optional(),
  codigo_postal: z.string().max(5).nullable().optional(),
  telefono: z.string().max(15).nullable().optional(),
  sexo: z.string().max(1).nullable().optional(),
  estado_civil: z.string().max(11).nullable().optional(),
  localidad: z.string().max(25).nullable().optional(),
  municipio: z.number().int().nullable().optional(),
  estado: z.number().int().nullable().optional(),
  pais: z.number().int().nullable().optional(),
  dependientes: z.number().int().nullable().optional(),
  posee_inmuebles: z.string().max(1).nullable().optional(),
  fecha_carta: z.string().datetime().nullable().optional(),
  email: z.string().max(30).nullable().optional(),
  nacionalidad: z.string().max(1).nullable().optional(),
  fecha_alta: z.string().datetime().nullable().optional(),
  celular: z.string().max(15).nullable().optional(),
  expediente: z.string().max(1).nullable().optional(),
  f_expediente: z.string().datetime().nullable().optional()
}).refine(
  (data) => Object.keys(data).length > 0,
  { message: 'At least one field must be provided for update' }
);