import { z } from 'zod';

// Schema for obtenerPlantilla response
export const ObtenerPlantillaResponseSchema = z.object({
  INTERNO: z.string(),
  CURP: z.string().nullable(),
  RFC: z.string().nullable(),
  NOEMPLEADO: z.string().nullable(),
  NOMBRE: z.string().nullable(),
  APELLIDO_PATERNO: z.string().nullable(),
  APELLIDO_MATERNO: z.string().nullable(),
  FECHA_NACIMIENTO: z.string().nullable(),
  SEXO: z.string().nullable(),
  ESTADO_CIVIL: z.string().nullable(),
  NACIONALIDAD: z.string().nullable(),
  FECHA_ALTA: z.string().nullable(),
  CELULAR: z.string().nullable(),
  EMAIL: z.string().nullable(),
  CALLE_NUMERO: z.string().nullable(),
  FRACCIONAMIENTO: z.string().nullable(),
  CODIGO_POSTAL: z.string().nullable(),
  LOCALIDAD: z.string().nullable(),
  MUNICIPIO: z.string().nullable(),
  ESTADO: z.string().nullable(),
  PAIS: z.string().nullable(),
  DEPENDIENTES: z.number().nullable(),
  POSEE_INMUEBLES: z.string().nullable(),
  FULLNAME: z.string().nullable(),
  FECHA_CARTA: z.string().nullable(),
  TELEFONO: z.string().nullable(),
  EXPEDIENTE: z.string().nullable(),
  F_EXPEDIENTE: z.string().nullable(),
  CLAVE_ORGANICA_0: z.string().nullable(),
  CLAVE_ORGANICA_1: z.string().nullable(),
  CLAVE_ORGANICA_2: z.string().nullable(),
  CLAVE_ORGANICA_3: z.string().nullable(),
  SUELDO: z.number().nullable(),
  OTRAS_PRESTACIONES: z.number().nullable(),
  QUINQUENIOS: z.number().nullable(),
  ACTIVO: z.string().nullable(),
  FECHA_MOV_ALT: z.string().nullable(),
  ORGS1: z.string().nullable(),
  ORGS2: z.string().nullable(),
  ORGS3: z.string().nullable(),
  ORGS: z.string().nullable(),
  DSUELDO: z.number().nullable(),
  DOTRAS_PRESTACIONES: z.number().nullable(),
  DQUINQUENIOS: z.number().nullable(),
  APLICAR: z.string().nullable(),
  BC: z.string().nullable(),
  PORCENTAJE: z.number().nullable()
});

export type ObtenerPlantillaResponse = z.infer<typeof ObtenerPlantillaResponseSchema>;