import { z } from 'zod';

export const AfiliadoOrgSchema = z.object({
  id: z.number().int(),
  afiliadoId: z.number().int(),
  nivel0Id: z.number().int().nullable(),
  nivel1Id: z.number().int().nullable(),
  nivel2Id: z.number().int().nullable(),
  nivel3Id: z.number().int().nullable(),
  claveOrganica0: z.string().max(30).nullable(),
  claveOrganica1: z.string().max(30).nullable(),
  claveOrganica2: z.string().max(30).nullable(),
  claveOrganica3: z.string().max(30).nullable(),
  interno: z.number().int().nullable(),
  sueldo: z.number().nullable(),
  otrasPrestaciones: z.number().nullable(),
  quinquenios: z.number().nullable(),
  activo: z.boolean(),
  fechaMovAlt: z.string().date().nullable(),
  orgs1: z.string().max(200).nullable(),
  orgs2: z.string().max(200).nullable(),
  orgs3: z.string().max(200).nullable(),
  orgs4: z.string().max(200).nullable(),
  dSueldo: z.string().max(200).nullable(),
  dOtrasPrestaciones: z.string().max(200).nullable(),
  dQuinquenios: z.string().max(200).nullable(),
  aplicar: z.boolean().nullable(),
  bc: z.string().max(30).nullable(),
  porcentaje: z.number().nullable(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime()
});

export const CreateAfiliadoOrgSchema = z.object({
  afiliadoId: z.number().int(),
  nivel0Id: z.number().int().nullable().optional(),
  nivel1Id: z.number().int().nullable().optional(),
  nivel2Id: z.number().int().nullable().optional(),
  nivel3Id: z.number().int().nullable().optional(),
  claveOrganica0: z.string().max(30).nullable().optional(),
  claveOrganica1: z.string().max(30).nullable().optional(),
  claveOrganica2: z.string().max(30).nullable().optional(),
  claveOrganica3: z.string().max(30).nullable().optional(),
  interno: z.number().int().nullable().optional(),
  sueldo: z.number().nullable().optional(),
  otrasPrestaciones: z.number().nullable().optional(),
  quinquenios: z.number().nullable().optional(),
  activo: z.boolean().optional().default(true),
  fechaMovAlt: z.string().date().nullable().optional(),
  orgs1: z.string().max(200).nullable().optional(),
  orgs2: z.string().max(200).nullable().optional(),
  orgs3: z.string().max(200).nullable().optional(),
  orgs4: z.string().max(200).nullable().optional(),
  dSueldo: z.string().max(200).nullable().optional(),
  dOtrasPrestaciones: z.string().max(200).nullable().optional(),
  dQuinquenios: z.string().max(200).nullable().optional(),
  aplicar: z.boolean().nullable().optional(),
  bc: z.string().max(30).nullable().optional(),
  porcentaje: z.number().nullable().optional()
});

export const UpdateAfiliadoOrgSchema = z.object({
  nivel0Id: z.number().int().nullable().optional(),
  nivel1Id: z.number().int().nullable().optional(),
  nivel2Id: z.number().int().nullable().optional(),
  nivel3Id: z.number().int().nullable().optional(),
  claveOrganica0: z.string().max(30).nullable().optional(),
  claveOrganica1: z.string().max(30).nullable().optional(),
  claveOrganica2: z.string().max(30).nullable().optional(),
  claveOrganica3: z.string().max(30).nullable().optional(),
  interno: z.number().int().nullable().optional(),
  sueldo: z.number().nullable().optional(),
  otrasPrestaciones: z.number().nullable().optional(),
  quinquenios: z.number().nullable().optional(),
  activo: z.boolean().optional(),
  fechaMovAlt: z.string().date().nullable().optional(),
  orgs1: z.string().max(200).nullable().optional(),
  orgs2: z.string().max(200).nullable().optional(),
  orgs3: z.string().max(200).nullable().optional(),
  orgs4: z.string().max(200).nullable().optional(),
  dSueldo: z.string().max(200).nullable().optional(),
  dOtrasPrestaciones: z.string().max(200).nullable().optional(),
  dQuinquenios: z.string().max(200).nullable().optional(),
  aplicar: z.boolean().nullable().optional(),
  bc: z.string().max(30).nullable().optional(),
  porcentaje: z.number().nullable().optional()
}).refine(
  (data) => Object.keys(data).length > 0,
  { message: 'At least one field must be provided for update' }
);