import assert from 'node:assert/strict';
import {DATABASE_ENVIRONMENTS,assertDatabaseEnvironment} from '../src/config/databaseEnvironments.js';

const development=DATABASE_ENVIRONMENTS.DESARROLLO;process.env.SQLSERVER_DB=development.sqlDatabase;process.env.FIREBIRD_DATABASE=development.firebirdDatabase;
assertDatabaseEnvironment('DESARROLLO',process.env.SQLSERVER_DB,process.env.FIREBIRD_DATABASE);
const {connectDatabase,closeDatabaseConnection}=await import('../src/db/mssql.js');const pool=await connectDatabase();
const expectedColumns:Record<string,Array<[string,string,number,boolean,boolean]>>={
  QnaAplicacionIntento:[['QnaAplicacionIntentoId','bigint',8,false,true],['IntentoUuid','uniqueidentifier',16,false,false],['QnaProcesoId','bigint',8,false,false],['LiquidacionSnapshotId','bigint',8,false,false],['AfectacionId','bigint',8,false,false],['NumeroIntento','int',4,false,false],['Estado','varchar',30,false,false],['Fase','varchar',30,false,false],['Activo','bit',1,false,false],['ClaimToken','uniqueidentifier',16,true,false],['ClaimTipo','varchar',20,true,false],['LeaseExpiraEn','datetime2',7,true,false],['Actor','nvarchar',200,false,false],['FechaCreacion','datetime2',7,false,false],['FechaActualizacion','datetime2',7,false,false]],
  QnaAplicacionIntentoEvento:[['QnaAplicacionIntentoEventoId','bigint',8,false,true],['QnaAplicacionIntentoId','bigint',8,false,false],['TipoEvento','varchar',30,false,false],['Estado','varchar',30,false,false],['Fase','varchar',30,false,false],['ClaimToken','uniqueidentifier',16,true,false],['Motivo','nvarchar',1000,true,false],['EvidenciaHash','char',64,true,false],['Actor','nvarchar',200,false,false],['FechaCreacion','datetime2',7,false,false]],
  QnaAplicacionResolucion:[['QnaAplicacionResolucionId','bigint',8,false,true],['QnaAplicacionIntentoId','bigint',8,false,false],['Resolucion','varchar',20,false,false],['MotivoNormalizado','nvarchar',300,false,false],['Evidencia','nvarchar',300,false,false],['EvidenciaHash','char',64,false,false],['Actor','nvarchar',200,false,false],['FechaCreacion','datetime2',7,false,false]],
};
try{const result=await pool.request().query(`
  SELECT DB_NAME() BaseDatos;
  SELECT o.name Tabla,c.column_id,c.name Columna,t.name Tipo,c.max_length,c.is_nullable,c.is_identity,c.scale,dc.definition Defecto
    FROM sys.tables o JOIN sys.schemas s ON s.schema_id=o.schema_id JOIN sys.columns c ON c.object_id=o.object_id JOIN sys.types t ON t.user_type_id=c.user_type_id
    LEFT JOIN sys.default_constraints dc ON dc.object_id=c.default_object_id
    WHERE s.name='liquidacion' AND o.name IN('QnaAplicacionIntento','QnaAplicacionIntentoEvento','QnaAplicacionResolucion') ORDER BY o.name,c.column_id;
  SELECT kc.name,kc.type,o.name Tabla,STRING_AGG(c.name,',')WITHIN GROUP(ORDER BY ic.key_ordinal) Columnas FROM sys.key_constraints kc JOIN sys.tables o ON o.object_id=kc.parent_object_id
    JOIN sys.index_columns ic ON ic.object_id=kc.parent_object_id AND ic.index_id=kc.unique_index_id AND ic.key_ordinal>0 JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id
    WHERE kc.parent_object_id IN(OBJECT_ID('liquidacion.QnaAplicacionIntento'),OBJECT_ID('liquidacion.QnaAplicacionIntentoEvento'),OBJECT_ID('liquidacion.QnaAplicacionResolucion')) GROUP BY kc.name,kc.type,o.name;
  SELECT fk.name,fk.is_disabled,fk.is_not_trusted,OBJECT_NAME(fk.parent_object_id) Tabla,OBJECT_SCHEMA_NAME(fk.referenced_object_id)+'.'+OBJECT_NAME(fk.referenced_object_id) Referencia,
    STRING_AGG(pc.name+'='+rc.name,',')WITHIN GROUP(ORDER BY fkc.constraint_column_id) Columnas FROM sys.foreign_keys fk
    JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id=fk.object_id JOIN sys.columns pc ON pc.object_id=fk.parent_object_id AND pc.column_id=fkc.parent_column_id
    JOIN sys.columns rc ON rc.object_id=fk.referenced_object_id AND rc.column_id=fkc.referenced_column_id
    WHERE fk.parent_object_id IN(OBJECT_ID('liquidacion.QnaAplicacionIntento'),OBJECT_ID('liquidacion.QnaAplicacionIntentoEvento'),OBJECT_ID('liquidacion.QnaAplicacionResolucion'))
    GROUP BY fk.name,fk.is_disabled,fk.is_not_trusted,fk.parent_object_id,fk.referenced_object_id;
  SELECT i.name,OBJECT_NAME(i.object_id) Tabla,i.is_unique,i.has_filter,i.filter_definition,i.is_disabled,
    STRING_AGG(CONCAT(c.name,':',ic.key_ordinal,':',ic.is_descending_key),',')WITHIN GROUP(ORDER BY ic.key_ordinal) Columnas
    FROM sys.indexes i JOIN sys.index_columns ic ON ic.object_id=i.object_id AND ic.index_id=i.index_id AND ic.key_ordinal>0 JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id
    WHERE i.name IN('UX_QnaAplicacionIntento_Activo','UX_QnaAplicacionIntento_Claim','IX_QnaAplicacionIntento_ProcesoFecha','IX_QnaAplicacionIntentoEvento_IntentoFecha') GROUP BY i.name,i.object_id,i.is_unique,i.has_filter,i.filter_definition,i.is_disabled;
  SELECT cc.name,cc.definition,cc.is_disabled,cc.is_not_trusted FROM sys.check_constraints cc WHERE cc.parent_object_id IN(OBJECT_ID('liquidacion.QnaAplicacionIntento'),OBJECT_ID('liquidacion.QnaAplicacionIntentoEvento'),OBJECT_ID('liquidacion.QnaAplicacionResolucion'));
  SELECT tr.name,tr.is_disabled,OBJECT_DEFINITION(tr.object_id) definition FROM sys.triggers tr WHERE tr.name IN('TR_QnaAplicacionIntentoEvento_Inmutable','TR_QnaAplicacionResolucion_Inmutable');
  SELECT COUNT_BIG(*) Inconsistentes FROM liquidacion.QnaAplicacionIntento WHERE NOT(
    (Estado='ACTIVO' AND Fase='FIREBIRD' AND Activo=1 AND ClaimToken IS NOT NULL AND ClaimTipo='FIREBIRD' AND LeaseExpiraEn IS NOT NULL) OR
    (Estado='INCIERTO' AND Fase='FIREBIRD' AND Activo=1 AND ClaimToken IS NULL AND ClaimTipo IS NULL AND LeaseExpiraEn IS NULL) OR
    (Estado='REVERTIDO' AND Fase='FIREBIRD' AND Activo=0 AND ClaimToken IS NULL AND ClaimTipo IS NULL AND LeaseExpiraEn IS NULL) OR
    (Estado='CONFIRMADO' AND Fase IN('LINEA','REVISA','BITACORA') AND Activo=1 AND ((ClaimToken IS NULL AND ClaimTipo IS NULL AND LeaseExpiraEn IS NULL) OR (ClaimToken IS NOT NULL AND ClaimTipo='RECUPERACION' AND LeaseExpiraEn IS NOT NULL))) OR
    (Estado='TERMINADO' AND Fase='TERMINADO' AND Activo=0 AND ClaimToken IS NULL AND ClaimTipo IS NULL AND LeaseExpiraEn IS NULL));
  WITH latest AS(SELECT t.*,ROW_NUMBER()OVER(PARTITION BY QnaProcesoId ORDER BY FechaCreacion DESC,QnaProcesoTransicionId DESC)rn FROM liquidacion.QnaProcesoTransicion t)
    SELECT EstadoDestino,COUNT_BIG(*) Cantidad,MIN(FechaCreacion) MasAntigua FROM latest WHERE rn=1 AND EstadoDestino IN('APLICANDO_FIREBIRD','APLICACION_INCIERTA') GROUP BY EstadoDestino;
  SELECT name,is_disabled FROM sys.indexes WHERE object_id=OBJECT_ID('liquidacion.QnaProcesoTransicion') AND name='IX_QnaProcesoTransicion_EstadoProcesoFecha';`);
  const sets=result.recordsets as Array<Array<Record<string,any>>>;assert.equal(sets[0][0].BaseDatos,development.sqlDatabase);
  for(const [table,spec] of Object.entries(expectedColumns)){const actual=sets[1].filter(row=>row.Tabla===table);assert.equal(actual.length,spec.length,`${table}: columnas inesperadas`);
    spec.forEach(([name,type,length,nullable,identity],index)=>{const row=actual[index];assert.deepEqual([row.Columna,row.Tipo,Number(row.max_length),Boolean(row.is_nullable),Boolean(row.is_identity)],[name,type,length,nullable,identity],`${table}.${name}`);
      if(type==='datetime2')assert.equal(Number(row.scale),3,`${table}.${name}: escala`);if(name.startsWith('Fecha'))assert.match(String(row.Defecto),/sysutcdatetime/i,`${table}.${name}: default`);});}
  const expectedKeys:Record<string,string>={PK_QnaAplicacionIntento:'QnaAplicacionIntentoId',PK_QnaAplicacionIntentoEvento:'QnaAplicacionIntentoEventoId',PK_QnaAplicacionResolucion:'QnaAplicacionResolucionId',UQ_QnaAplicacionIntento_Uuid:'IntentoUuid',UQ_QnaAplicacionIntento_Numero:'QnaProcesoId,NumeroIntento',UQ_QnaAplicacionResolucion_Intento:'QnaAplicacionIntentoId'};
  assert.equal(sets[2].length,Object.keys(expectedKeys).length,'Keys fase 11 inesperadas');for(const key of sets[2])assert.equal(key.Columnas,expectedKeys[key.name],`${key.name}: columnas`);
  assert.equal(sets[3].length,5,'FKs fase 11 incompletas');for(const fk of sets[3])assert.deepEqual([Boolean(fk.is_disabled),Boolean(fk.is_not_trusted)],[false,false],`${fk.name} no confiable`);
  const expectedFks:Record<string,[string,string]>={FK_QnaAplicacionIntento_Proceso:['liquidacion.QnaProceso','QnaProcesoId=QnaProcesoId'],FK_QnaAplicacionIntento_Snapshot:['liquidacion.QnaSnapshot','LiquidacionSnapshotId=LiquidacionSnapshotId'],FK_QnaAplicacionIntento_Afectacion:['afec.BitacoraAfectacionOrg','AfectacionId=AfectacionId'],FK_QnaAplicacionIntentoEvento_Intento:['liquidacion.QnaAplicacionIntento','QnaAplicacionIntentoId=QnaAplicacionIntentoId'],FK_QnaAplicacionResolucion_Intento:['liquidacion.QnaAplicacionIntento','QnaAplicacionIntentoId=QnaAplicacionIntentoId']};for(const fk of sets[3])assert.deepEqual([fk.Referencia,fk.Columnas],expectedFks[fk.name],`${fk.name}: enlace`);
  assert.equal(sets[4].length,4,'Indices fase 11 incompletos');const indexes=new Map(sets[4].map(x=>[x.name,x]));assert.match(String(indexes.get('UX_QnaAplicacionIntento_Activo')?.filter_definition),/Activo.*1/i);assert.match(String(indexes.get('UX_QnaAplicacionIntento_Claim')?.filter_definition),/ClaimToken.*NOT NULL/i);assert.equal(indexes.get('UX_QnaAplicacionIntento_Activo')?.Columnas,'QnaProcesoId:1:0');assert.equal(indexes.get('UX_QnaAplicacionIntento_Claim')?.Columnas,'QnaProcesoId:1:0');assert.equal(indexes.get('IX_QnaAplicacionIntento_ProcesoFecha')?.Columnas,'QnaProcesoId:1:0,FechaCreacion:2:1,QnaAplicacionIntentoId:3:1');assert.equal(indexes.get('IX_QnaAplicacionIntentoEvento_IntentoFecha')?.Columnas,'QnaAplicacionIntentoId:1:0,FechaCreacion:2:0,QnaAplicacionIntentoEventoId:3:0');assert.equal(Boolean(indexes.get('UX_QnaAplicacionIntento_Activo')?.is_unique),true);assert.equal(Boolean(indexes.get('UX_QnaAplicacionIntento_Claim')?.is_unique),true);for(const index of sets[4])assert.equal(Boolean(index.is_disabled),false,`${index.name} deshabilitado`);
  const checks=new Map(sets[5].map(x=>[x.name,x]));for(const name of ['CK_QnaAplicacionIntento_Estado','CK_QnaAplicacionIntento_Fase','CK_QnaAplicacionIntento_Claim','CK_QnaAplicacionIntento_Invariante','CK_QnaAplicacionIntentoEvento_Tipo','CK_QnaAplicacionResolucion_Valor']){const check=checks.get(name);assert(check,`Falta ${name}`);assert.deepEqual([Boolean(check.is_disabled),Boolean(check.is_not_trusted)],[false,false],`${name} no confiable`);}
  assert.match(String(checks.get('CK_QnaAplicacionIntento_Invariante').definition),/REVERTIDO/i);assert.match(String(checks.get('CK_QnaAplicacionIntento_Invariante').definition),/RECUPERACION/i);assert.match(String(checks.get('CK_QnaAplicacionIntentoEvento_Tipo').definition),/CLAIM_RENOVADO/i);
  assert.equal(sets[6].length,2,'Triggers inmutables incompletos');for(const trigger of sets[6]){assert.equal(Boolean(trigger.is_disabled),false,`${trigger.name} deshabilitado`);assert.match(String(trigger.definition),/AFTER UPDATE,DELETE/i);assert.match(String(trigger.definition),/THROW 5163[12]/);}
  assert.equal(Number(sets[7][0].Inconsistentes),0,'Hay invariantes contradictorias');assert.equal(sets[9].length,1,'Falta indice de ultima transicion');
  console.log(JSON.stringify({status:'QNA_PHASE11_STATE_VERIFIER_DESARROLLO_OK',manualResolutionRequired:sets[8]},null,2));
}finally{await closeDatabaseConnection();}
